
site_name: 'CloudDefend'

repo_url: https://github.com/RicardoMourao-py/CloudDefend.git
repo_name: RicardoMourao-py/CloudDefend

theme:
  custom_dir: docs-src/.override
  logo: img/favicon.png
  favicon: img/favicon.png
  features:
    - instant
    - navigation.expand
    - content.code.copy
    - navigation.top
    - tabs: true
  name: 'material'
  icon:
    repo: fontawesome/brands/github 
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: 'blue'
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'blue'
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

      accent: 'pink'

  font:
    text: Roboto
    code: Roboto Mono


# repo
docs_dir: docs-src
site_dir: docs

nav:
  - Home: index.md
  - init.md
  - hostedS3.md
  - apiProxy.md
  - waf.md

# Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true


plugins:
    - search
